logfile: <%= @log_file %>
loglevel: <%= @log_level %>
frequency: <%= @frequency %>
include: services.d/

<% if @tags and not @tags.empty? %>
tags:
<%= @tags.map { |t| "  - #{t}" }.join("\n") %>
<% end %>

storages:
  -
    name: copperegg
    api_key: <%= @api_key %>
