app:
  logPath: '<%= @log_file_path %>'
httpServer:
  port: <%= @http_port %>
  apiKey: '<%= @api_key %>'
proxy:
  listenPort: <%= @proxy_port %>
  janusAddress: '<%= @proxy_upstream %>'
cmApi:
  baseUrl: '<%= @cm_api_base_url %>'
  apiKey: '<%= @cm_api_key %>'
