app:
  logPath: '/var/log/cm-janus/cm-janus.log'
httpServer:
  port: <%= @http_server_port %>
  apiKey: '<%= @http_server_api_key %>'
proxy:
  listenPort: <%= @websockets_listen_port %>
  janusAddress: '<%= @websockets_janus_address %>'
cmApi:
  baseUrl: '<%= @cm_api_base_url %>'
  apiKey:  '<%= @cm_api_key %>'
