logPath: '/var/log/cm-janus/cm-janus.log'
httpServer:
  port: <%= @http_server_port %>
  apiKey: '<%= @http_server_api_key %>'
webSocketServer:
  port: <%= @websockets_listen_port %>
janus:
  webSocketAddress: '<%= @janus_websocket_address %>'
  httpAddress: '<%= @janus_http_address %>'
cmApi:
  baseUrl: '<%= @cm_api_base_url %>'
  apiKey:  '<%= @cm_api_key %>'
cmApplication:
  path: '<%= @cm_application_path %>'
jobManager:
  jobsPath: '<%= @jobs_path %>'
  tempFilesPath: '/var/lib/cm-janus/jobs-temp-files'
  handlersConfiguration:
    'janus.plugin.cm.audioroom:audio-recording-finished':
      convertCommand: 'nice -n <%= @jobs_priority %>  lame <%%= wavFile %> <%%= mp3File %>'
    'janus.plugin.cm.rtpbroadcast:recording-finished':
      mergeCommand: 'nice -n <%= @jobs_priority %> mjr2webm <%%= videoMjrFile %> <%%= audioMjrFile %> <%%= webmFile %>'
    'janus.plugin.cm.rtpbroadcast:thumbnailing-finished':
      createThumbnailCommand: 'nice -n <%= @jobs_priority %> mjr2png <%%= videoMjrFile %> <%= @thumbnailWidth %> <%= @thumbnailHeight %> <%%= pngFile %>'

