port: <%= @port %>
mongodb:
  host: '<%= @mongodb_host %>'
  port: <%= @mongodb_port %>
  db: '<%= @mongodb_db %>'
<% if @pulsar_repo || @pulsar_branch %>
pulsar:
  repo: '<%= @pulsar_repo %>'
  branch: '<%= @pulsar_branch %>'
<% end -%>
logPath: '<%= @log_dir %>/pulsar-rest-api.log'
<% if @authentication -%>
authentication:
  githubOauthId: '<%= @authentication['github_oauth_id'] %>'
  githubOauthSecret: '<%= @authentication['github_oauth_secret'] %>'
  githubOrg: '<%= @authentication['github_org'] %>'
  baseUrl: '<%= @authentication['base_url'] %>'
<% if @authentication['authorization'] -%>
  authorization:
    read: <%= @authentication['authorization']['read'] %>
    write: <%= @authentication['authorization']['write'] %>
<% end -%>
<% end -%>
